# Generated by Django 6.0.5 on 2026-05-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroponto',
            name='distancia_metros',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='localizacao_valida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
