# Generated by Django 6.0.5 on 2026-05-16 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0003_funcionario_carga_horaria_diaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoBancoHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horas_trabalhadas', models.DurationField()),
                ('horas_previstas', models.DurationField()),
                ('saldo', models.DurationField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
            ],
        ),
    ]
