# Generated by Django 6.0.5 on 2026-05-16 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_horas', '0001_initial'),
        ('funcionarios', '0003_funcionario_carga_horaria_diaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoBancoHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('saldo_final', models.DurationField()),
                ('fechado_em', models.DateTimeField(auto_now_add=True)),
                ('fechado', models.BooleanField(default=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
            ],
        ),
    ]
