# Generated by Django 6.0.5 on 2026-05-16 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banco_horas', '0002_fechamentobancohoras'),
        ('funcionarios', '0003_funcionario_carga_horaria_diaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompensacaoBancoHoras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=20)),
                ('quantidade', models.DurationField()),
                ('motivo', models.TextField()),
                ('aprovado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
            ],
        ),
    ]
